name: CI/CD Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarCloud scanner
        uses: SonarSource/sonarcloud-github-action@v2

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"vuthang692005_emnhanvien" /o:"vuthang692005" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          dotnet restore
          dotnet build
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - run: dotnet test --no-build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
