name: CI/CD Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -f Dockerfile -t tungaris/ip-backend-docker:latest .

      - name: Push Docker image to Docker Hub
        run: docker push tungaris/ip-backend-docker:latest

      - name: Trigger Deploy on Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}