name: Deploy to Render

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
