name: CI Pipeline

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Clean
        run: |
          rm -rf emnhanvien/obj/ emnhanvien/bin/
          rm -rf emnhanvien.Tests/obj/ emnhanvien.Tests/bin/

      - name: Restore and Build
        run: |
          dotnet restore emnhanvien/emnhanvien.sln
          dotnet restore emnhanvien.Tests/emnhanvien.Tests.csproj
          dotnet build emnhanvien/emnhanvien.sln --no-restore --configuration Release

      - name: Run tests
        run: |
          cd emnhanvien.Tests
          dotnet test --configuration Release --verbosity normal --logger "console;verbosity=detailed"

  sonar-analysis:
    if: github.event_name == 'pull_request'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add dotnet tools to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd emnhanvien
          dotnet sonarscanner begin /k:"vuthang692005_emnhanvien" /o:"vuthang692005" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          dotnet restore
          dotnet build --no-restore
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
